# Generated by Django 2.1.1 on 2018-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/46761582_183035712641249_1139093754318159872_n.jpg', upload_to='profile_pics'),
        ),
    ]
