# Generated by Django 2.0.8 on 2018-11-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_geo'),
        ('account', '0002_auto_20181129_1617'),
    ]

    operations = [
    ]
