# Generated by Django 2.0.8 on 2018-12-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_merge_20181130_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=113)),
                ('self_atc', models.DecimalField(decimal_places=1, max_digits=2)),
                ('self_ist', models.DecimalField(decimal_places=1, max_digits=2)),
                ('self_amb', models.DecimalField(decimal_places=1, max_digits=2)),
                ('self_fun', models.DecimalField(decimal_places=1, max_digits=2)),
                ('self_int', models.DecimalField(decimal_places=1, max_digits=2)),
                ('self_sin', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_atc', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_ist', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_amb', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_fun', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_int', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prtn_sin', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
