# Generated by Django 2.0.8 on 2018-12-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181206_1742'),
        ('account', '0005_taste'),
    ]

    operations = [
    ]
