# Generated by Django 2.0.8 on 2019-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20181207_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/JFBLK.jpg', upload_to='profile_pics'),
        ),
    ]
