# Generated by Django 2.0.8 on 2018-12-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20181207_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taste',
            name='prtn_ist',
        ),
        migrations.RemoveField(
            model_name='taste',
            name='self_ist',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/JFBLK.jpg', upload_to='profile_pics'),
        ),
    ]
