# Generated by Django 2.0.8 on 2019-01-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181228_1113'),
        ('account', '0007_auto_20190103_1610'),
    ]

    operations = [
    ]
